2021-02-19 13:50:39,742 INFO    MainThread:21852 [wandb_setup.py:_flush():70] setting env: {}
2021-02-19 13:50:39,742 INFO    MainThread:21852 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-02-19 13:50:39,742 INFO    MainThread:21852 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-19 13:50:39,743 INFO    MainThread:21852 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fde89ef6dc0>
2021-02-19 13:50:39,743 INFO    MainThread:21852 [wandb_init.py:_log_setup():319] Logging user logs to /home/johannbs/Desktop/IceCube_GNN/wandb/run-20210219_135039-13la5eew/logs/debug.log
2021-02-19 13:50:39,743 INFO    MainThread:21852 [wandb_init.py:_log_setup():320] Logging internal logs to /home/johannbs/Desktop/IceCube_GNN/wandb/run-20210219_135039-13la5eew/logs/debug-internal.log
2021-02-19 13:50:39,743 INFO    MainThread:21852 [wandb_init.py:init():351] calling init triggers
2021-02-19 13:50:39,743 INFO    MainThread:21852 [wandb_init.py:init():356] wandb.init called with sweep_config: {}
config: {}
2021-02-19 13:50:39,743 INFO    MainThread:21852 [wandb_init.py:init():404] starting backend
2021-02-19 13:50:39,786 INFO    MainThread:21852 [backend.py:ensure_launched():81] starting backend process...
2021-02-19 13:50:39,841 ERROR   MainThread:21852 [wandb_init.py:init():745] error
Traceback (most recent call last):
  File "/home/johannbs/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 719, in init
    run = wi.init()
  File "/home/johannbs/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 406, in init
    backend.ensure_launched(
  File "/home/johannbs/anaconda3/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 83, in ensure_launched
    self.wandb_process.start()
  File "/home/johannbs/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/johannbs/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/johannbs/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/johannbs/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/johannbs/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/johannbs/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
