GPU detected
Loading data to memory
  0%|                                                   | 0/196 [00:00<?, ?it/s]WARNING:tensorflow:Gradients do not exist for variables ['model/dense_3/kernel:0', 'model/dense_3/bias:0', 'model/dense_6/kernel:0', 'model/dense_6/bias:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['model/dense_3/kernel:0', 'model/dense_3/bias:0', 'model/dense_6/kernel:0', 'model/dense_6/bias:0'] when minimizing the loss.
[0;31m---------------------------------------------------------------------------[0m
[0;31mInvalidArgumentError[0m                      Traceback (most recent call last)
[0;32m~/Desktop/IceCube_GNN/train_likelihood.py[0m in [0;36m<module>[0;34m[0m
[1;32m    229[0m     [0minputs[0m[0;34m,[0m [0mtargets[0m  [0;34m=[0m [0mbatch[0m[0;34m[0m[0;34m[0m[0m
[1;32m    230[0m     [0minputs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;34m:[0m[0;36m3[0m[0;34m][0m [0;34m=[0m [0minputs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;34m:[0m[0;36m3[0m[0;34m][0m [0;34m/[0m [0;36m1000[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 231[0;31m     [0mout[0m              [0;34m=[0m [0mtrain_step[0m[0;34m([0m[0minputs[0m[0;34m,[0m [0mtargets[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    232[0m     [0mloss[0m            [0;34m+=[0m [0mout[0m[0;34m[0m[0;34m[0m[0m
[1;32m    233[0m [0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py[0m in [0;36m__call__[0;34m(self, *args, **kwds)[0m
[1;32m    826[0m     [0mtracing_count[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mexperimental_get_tracing_count[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    827[0m     [0;32mwith[0m [0mtrace[0m[0;34m.[0m[0mTrace[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_name[0m[0;34m)[0m [0;32mas[0m [0mtm[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 828[0;31m       [0mresult[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_call[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    829[0m       [0mcompiler[0m [0;34m=[0m [0;34m"xla"[0m [0;32mif[0m [0mself[0m[0;34m.[0m[0m_experimental_compile[0m [0;32melse[0m [0;34m"nonXla"[0m[0;34m[0m[0;34m[0m[0m
[1;32m    830[0m       [0mnew_tracing_count[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mexperimental_get_tracing_count[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py[0m in [0;36m_call[0;34m(self, *args, **kwds)[0m
[1;32m    886[0m         [0;31m# Lifting succeeded, so variables are initialized and we can run the[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    887[0m         [0;31m# stateless function.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 888[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_stateless_fn[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    889[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    890[0m       [0m_[0m[0;34m,[0m [0m_[0m[0;34m,[0m [0m_[0m[0;34m,[0m [0mfiltered_flat_args[0m [0;34m=[0m[0;31m [0m[0;31m\[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py[0m in [0;36m__call__[0;34m(self, *args, **kwargs)[0m
[1;32m   2940[0m       (graph_function,
[1;32m   2941[0m        filtered_flat_args) = self._maybe_define_function(args, kwargs)
[0;32m-> 2942[0;31m     return graph_function._call_flat(
[0m[1;32m   2943[0m         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
[1;32m   2944[0m [0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py[0m in [0;36m_call_flat[0;34m(self, args, captured_inputs, cancellation_manager)[0m
[1;32m   1916[0m         and executing_eagerly):
[1;32m   1917[0m       [0;31m# No tape is watching; skip to running the function.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1918[0;31m       return self._build_call_outputs(self._inference_function.call(
[0m[1;32m   1919[0m           ctx, args, cancellation_manager=cancellation_manager))
[1;32m   1920[0m     forward_backward = self._select_forward_and_backward_functions(

[0;32m~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py[0m in [0;36mcall[0;34m(self, ctx, args, cancellation_manager)[0m
[1;32m    553[0m       [0;32mwith[0m [0m_InterpolateFunctionError[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    554[0m         [0;32mif[0m [0mcancellation_manager[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 555[0;31m           outputs = execute.execute(
[0m[1;32m    556[0m               [0mstr[0m[0;34m([0m[0mself[0m[0;34m.[0m[0msignature[0m[0;34m.[0m[0mname[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    557[0m               [0mnum_outputs[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0m_num_outputs[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py[0m in [0;36mquick_execute[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)[0m
[1;32m     57[0m   [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     58[0m     [0mctx[0m[0;34m.[0m[0mensure_initialized[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 59[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
[0m[1;32m     60[0m                                         inputs, attrs, num_outputs)
[1;32m     61[0m   [0;32mexcept[0m [0mcore[0m[0;34m.[0m[0m_NotOkStatusException[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mInvalidArgumentError[0m:  Input is not invertible.
	 [[node gradient_tape/MatrixInverse (defined at /home/johannbs/Desktop/IceCube_GNN/train_likelihood.py:155) ]] [Op:__inference_train_step_2691]

Errors may have originated from an input operation.
Input Source operations connected to node gradient_tape/MatrixInverse:
 diag (defined at /home/johannbs/Desktop/IceCube_GNN/loss_functions.py:101)

Function call stack:
train_step


Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
ecc_conv (ECCConv)           multiple                  6656      
_________________________________________________________________
gcn_conv (GCNConv)           multiple                  1024      
_________________________________________________________________
gcn_conv_1 (GCNConv)         multiple                  2048      
_________________________________________________________________
gcn_conv_2 (GCNConv)         multiple                  8192      
_________________________________________________________________
gcn_conv_3 (GCNConv)         multiple                  32768     
_________________________________________________________________
global_avg_pool (GlobalAvgPo multiple                  0         
_________________________________________________________________
dense (Dense)                multiple                  131584    
_________________________________________________________________
dense_1 (Dense)              multiple                  262656    
_________________________________________________________________
dense_2 (Dense)              multiple                  131328    
_________________________________________________________________
dropout (Dropout)            multiple                  0         
_________________________________________________________________
dropout_1 (Dropout)          multiple                  0         
_________________________________________________________________
dropout_2 (Dropout)          multiple                  0         
_________________________________________________________________
batch_normalization (BatchNo multiple                  2048      
_________________________________________________________________
batch_normalization_1 (Batch multiple                  2048      
_________________________________________________________________
batch_normalization_2 (Batch multiple                  1024      
_________________________________________________________________
dense_3 (Dense)              multiple                  8224      
_________________________________________________________________
dense_4 (Dense)              multiple                  8224      
_________________________________________________________________
dense_5 (Dense)              multiple                  99        
_________________________________________________________________
dense_6 (Dense)              multiple                  8224      
_________________________________________________________________
dense_7 (Dense)              multiple                  8224      
_________________________________________________________________
dense_8 (Dense)              multiple                  99        
=================================================================
Total params: 614,470
Trainable params: 611,910
Non-trainable params: 2,560
_________________________________________________________________

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m~/anaconda3/lib/python3.8/site-packages/IPython/core/magics/execution.py[0m in [0;36mrun[0;34m(self, parameter_s, runner, file_finder)[0m
[1;32m    702[0m             [0mfpath[0m [0;34m=[0m [0marg_lst[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 703[0;31m             [0mfilename[0m [0;34m=[0m [0mfile_finder[0m[0;34m([0m[0mfpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    704[0m         [0;32mexcept[0m [0mIndexError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/IPython/utils/path.py[0m in [0;36mget_py_filename[0;34m(name, force_win32)[0m
[1;32m    108[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 109[0;31m         [0;32mraise[0m [0mIOError[0m[0;34m([0m[0;34m'File `%r` not found.'[0m [0;34m%[0m [0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    110[0m [0;34m[0m[0m

[0;31mOSError[0m: File `'GCN_likelihood.py'` not found.

During handling of the above exception, another exception occurred:

[0;31mException[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-3-064fca157ad8>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mget_ipython[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mrun_line_magic[0m[0;34m([0m[0;34m'run'[0m[0;34m,[0m [0;34m'GCN_likelihood'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py[0m in [0;36mrun_line_magic[0;34m(self, magic_name, line, _stack_depth)[0m
[1;32m   2325[0m                 [0mkwargs[0m[0;34m[[0m[0;34m'local_ns'[0m[0;34m][0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mget_local_scope[0m[0;34m([0m[0mstack_depth[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2326[0m             [0;32mwith[0m [0mself[0m[0;34m.[0m[0mbuiltin_trap[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2327[0;31m                 [0mresult[0m [0;34m=[0m [0mfn[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2328[0m             [0;32mreturn[0m [0mresult[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2329[0m [0;34m[0m[0m

[0;32m<decorator-gen-52>[0m in [0;36mrun[0;34m(self, parameter_s, runner, file_finder)[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/IPython/core/magic.py[0m in [0;36m<lambda>[0;34m(f, *a, **k)[0m
[1;32m    185[0m     [0;31m# but it's overkill for just that one bit of state.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    186[0m     [0;32mdef[0m [0mmagic_deco[0m[0;34m([0m[0marg[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 187[0;31m         [0mcall[0m [0;34m=[0m [0;32mlambda[0m [0mf[0m[0;34m,[0m [0;34m*[0m[0ma[0m[0;34m,[0m [0;34m**[0m[0mk[0m[0;34m:[0m [0mf[0m[0;34m([0m[0;34m*[0m[0ma[0m[0;34m,[0m [0;34m**[0m[0mk[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    188[0m [0;34m[0m[0m
[1;32m    189[0m         [0;32mif[0m [0mcallable[0m[0;34m([0m[0marg[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/IPython/core/magics/execution.py[0m in [0;36mrun[0;34m(self, parameter_s, runner, file_finder)[0m
[1;32m    712[0m             [0;32mif[0m [0mos[0m[0;34m.[0m[0mname[0m [0;34m==[0m [0;34m'nt'[0m [0;32mand[0m [0mre[0m[0;34m.[0m[0mmatch[0m[0;34m([0m[0;34mr"^'.*'$"[0m[0;34m,[0m[0mfpath[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    713[0m                 [0mwarn[0m[0;34m([0m[0;34m'For Windows, use double quotes to wrap a filename: %run "mypath\\myfile.py"'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 714[0;31m             [0;32mraise[0m [0mException[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    715[0m         [0;32mexcept[0m [0mTypeError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    716[0m             [0;32mif[0m [0mfpath[0m [0;32min[0m [0msys[0m[0;34m.[0m[0mmeta_path[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mException[0m: File `'GCN_likelihood.py'` not found.

[23;0t